name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: NuGet pack
      run : dotnet pack src --configuration Release --no-restore --no-build
    - uses: actions/upload-artifact@v2
      with:
        name: NugetAudit
        path: nupkg/*.nupkg
    - name: Upload Nuget to GitHub packages
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/konek3/index.json -n github -u konek3 -p secrets.GITHUB_TOKEN --store-password-in-clear-text
        dotnet nuget push "nupkg/*.nupkg" --source "github"
        
